### ISSUE TITLE
Request for showing this off in a video

### ISSUE THREAD

**Issue by QuifixOfficial** [BlackCorsair/install-jdk-on-steam-deck#1]
Greetings,
After some search on the internet I found this page on github and I cannot thank you enough for creating the script. No one did a video about this on YouTube so a lot of people probably won't even bother to search for the Github page. Am I allowed to create a video showing off how to install java on the Steam Deck? If not I would highly suggest you make one yourself

**Comment by BlackCorsair** [comment]
hey! Thanks for the comment. Sorry about the late response.

> Am I allowed to create a video showing off how to install java on the Steam Deck?

Of course :) I didn't thought about it but maybe it's a good idea. If you do, keep me posted so I link the youtube video in the README.

BR
