### ISSUE TITLE
Uninstall Current Installed Java

### ISSUE THREAD

**Issue by BahaminShahriari** [BlackCorsair/install-jdk-on-steam-deck#4]
Hello,

I want to use a java game that only accepts Java 8, is there any way to undo this installation?

**Comment by BlackCorsair** [comment]
Hi,
You can delete the directory that the script creates:
```bash
rm -rf "${HOME}/.local/jdk"
```

And then remove the `JAVA_HOME` and `PATH` variables that the script adds in `~/.profile`.

BR
