### ISSUE TITLE
It is installed but how do you run a .jar file

### ISSUE THREAD

**Issue by sevrick** [BlackCorsair/install-jdk-on-steam-deck#9]
So I was confused when you said "Exec a checksum of the file using the official sha256 checksum"
I assumed it ment copy the linux link and paste it into a the terminal and run it. Which I did and it said it successfully installed but how do I run my .jar file now that it is installed?

**Comment by BlackCorsair** [comment]
Hi! to run a jar using java it should be: `java -jar <path-to-executable>`

**Comment by sevrick** [comment]
Ok it worked but I am new to linux. I would like it run when I double click on it. I know that you can change what program you use to open it by default, but I don't know where it is located.
